<?xml version="1.0"  encoding = "UTF-8" ?>
<wsdl:definitions xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:random="http://ws.com/Service/xsd/random-schema"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:tns="http://ws.com/Service/samplews-ns"
    targetNamespace="http://ws.com/Service/samplews-ns">
    
    <wsdl:types>
        <xs:schema>
            <xs:import namespace="http://ws.com/Service/xsd/random-schema"
                schemaLocation="xsd/RandomService.xsd" />
        </xs:schema>
    </wsdl:types>

    <wsdl:message name="GetRandomRequest">
        <wsdl:part element="random:GetRandomRequest" name="GetRandomRequest" />
    </wsdl:message>
    <wsdl:message name="GetRandomResponse">
        <wsdl:part element="random:GetRandomResponse"
            name="GetRandomResponse" />
    </wsdl:message>
    <wsdl:message name="GetRandomFault">
        <wsdl:part element="random:GetRandomFault" name="GetRandomFault" />
    </wsdl:message>

    <wsdl:portType name="SampleServiceOperationsPortType">
        <wsdl:operation name="random">
            <wsdl:documentation>Returns a random value
            </wsdl:documentation>
            <wsdl:input message="tns:GetRandomRequest" name="GetRandomRequest" />
            <wsdl:output message="tns:GetRandomResponse" name="GetRandomResponse" />
            <wsdl:fault message="tns:GetRandomFault" name="GetRandomFault" />
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="SampleServiceOperationsPortTypeSoap"
        type="tns:SampleServiceOperationsPortType">
        <soap:binding style="document"
            transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="random">
            <soap:operation soapAction="/Service/random" />
            <wsdl:input name="GetRandomRequest">
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output name="GetRandomResponse">
                <soap:body use="literal" />
            </wsdl:output>
            <wsdl:fault name="GetRandomFault">
                <soap:fault use="literal" name="GetRandomFault" />
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="SampleServiceOperationsPortTypeSoap">
        <wsdl:port binding="tns:SampleServiceOperationsPortTypeSoap"
            name="SampleServiceOperationsPortTypeSoap">
            <soap:address location="/Service/ws-operations" />
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
