//created on: Jul 29, 2013
//@author: Venky

package SlfPmAppRules

import com.slf.pmapp.models.Resource;
import com.slf.pmapp.models.Track;
import com.slf.pmapp.models.Allocation;
import org.springframework.validation.Errors;
import org.springframework.validation.ValidationUtils;

//list any import classes here.
 
//declare any global variables here


rule "Resource Name should not be empty"
when
  	$r: Resource( name == "")  
  	$e: Errors()
then
	$e.rejectValue("name", "err1", "DRL:Ensure Name is input");
end

rule "Track Name should not be empty"
when
  	$t: Track( name == "")  
  	$e: Errors()
then
	$e.rejectValue("name", "err2", "DRL:Name is required");
end


