
package com.ws.service.samplews_ns;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "GetRandomFault", targetNamespace = "http://ws.com/Service/xsd/random-schema")
public class GetRandomFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private com.ws.service.xsd.random_schema.GetRandomFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public GetRandomFault(String message, com.ws.service.xsd.random_schema.GetRandomFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public GetRandomFault(String message, com.ws.service.xsd.random_schema.GetRandomFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.ws.service.xsd.random_schema.GetRandomFault
     */
    public com.ws.service.xsd.random_schema.GetRandomFault getFaultInfo() {
        return faultInfo;
    }

}
