
package com.ws.service.samplews_ns;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SampleServiceOperationsPortTypeSoap", targetNamespace = "http://ws.com/Service/samplews-ns", wsdlLocation = "http://localhost:8080/SLFPMApp/services/SampleService.wsdl")
public class SampleServiceOperationsPortTypeSoap
    extends Service
{

    private final static URL SAMPLESERVICEOPERATIONSPORTTYPESOAP_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/SLFPMApp/services/SampleService.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        SAMPLESERVICEOPERATIONSPORTTYPESOAP_WSDL_LOCATION = url;
    }

    public SampleServiceOperationsPortTypeSoap(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SampleServiceOperationsPortTypeSoap() {
        super(SAMPLESERVICEOPERATIONSPORTTYPESOAP_WSDL_LOCATION, new QName("http://ws.com/Service/samplews-ns", "SampleServiceOperationsPortTypeSoap"));
    }

    /**
     * 
     * @return
     *     returns SampleServiceOperationsPortType
     */
    @WebEndpoint(name = "SampleServiceOperationsPortTypeSoap")
    public SampleServiceOperationsPortType getSampleServiceOperationsPortTypeSoap() {
        return (SampleServiceOperationsPortType)super.getPort(new QName("http://ws.com/Service/samplews-ns", "SampleServiceOperationsPortTypeSoap"), SampleServiceOperationsPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SampleServiceOperationsPortType
     */
    @WebEndpoint(name = "SampleServiceOperationsPortTypeSoap")
    public SampleServiceOperationsPortType getSampleServiceOperationsPortTypeSoap(WebServiceFeature... features) {
        return (SampleServiceOperationsPortType)super.getPort(new QName("http://ws.com/Service/samplews-ns", "SampleServiceOperationsPortTypeSoap"), SampleServiceOperationsPortType.class, features);
    }

}
