
package com.ws.service.samplews_ns;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.ws.service.xsd.random_schema.GetRandomRequest;
import com.ws.service.xsd.random_schema.GetRandomResponse;
import com.ws.service.xsd.random_schema.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SampleServiceOperationsPortType", targetNamespace = "http://ws.com/Service/samplews-ns")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SampleServiceOperationsPortType {


    /**
     * Returns a random value
     *             
     * 
     * @param getRandomRequest
     * @return
     *     returns com.ws.service.xsd.random_schema.GetRandomResponse
     * @throws GetRandomFault
     */
    @WebMethod(action = "/Service/random")
    @WebResult(name = "GetRandomResponse", targetNamespace = "http://ws.com/Service/xsd/random-schema", partName = "GetRandomResponse")
    public GetRandomResponse random(
        @WebParam(name = "GetRandomRequest", targetNamespace = "http://ws.com/Service/xsd/random-schema", partName = "GetRandomRequest")
        GetRandomRequest getRandomRequest)
        throws GetRandomFault
    ;

}
