
package com.slf.pmapp.service.resourceimportws_ns;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ResourceImportServiceOperationsPortTypeSoap", targetNamespace = "http://slf.com/pmapp/service/resourceimportws-ns", wsdlLocation = "http://localhost:8080/SLFPMApp/services/ResourceImportService.wsdl")
public class ResourceImportServiceOperationsPortTypeSoap
    extends Service
{

    private final static URL RESOURCEIMPORTSERVICEOPERATIONSPORTTYPESOAP_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/SLFPMApp/services/ResourceImportService.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        RESOURCEIMPORTSERVICEOPERATIONSPORTTYPESOAP_WSDL_LOCATION = url;
    }

    public ResourceImportServiceOperationsPortTypeSoap(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ResourceImportServiceOperationsPortTypeSoap() {
        super(RESOURCEIMPORTSERVICEOPERATIONSPORTTYPESOAP_WSDL_LOCATION, new QName("http://slf.com/pmapp/service/resourceimportws-ns", "ResourceImportServiceOperationsPortTypeSoap"));
    }

    /**
     * 
     * @return
     *     returns ResourceImportServiceOperationsPortType
     */
    @WebEndpoint(name = "ResourceImportServiceOperationsPortTypeSoap")
    public ResourceImportServiceOperationsPortType getResourceImportServiceOperationsPortTypeSoap() {
        return (ResourceImportServiceOperationsPortType)super.getPort(new QName("http://slf.com/pmapp/service/resourceimportws-ns", "ResourceImportServiceOperationsPortTypeSoap"), ResourceImportServiceOperationsPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ResourceImportServiceOperationsPortType
     */
    @WebEndpoint(name = "ResourceImportServiceOperationsPortTypeSoap")
    public ResourceImportServiceOperationsPortType getResourceImportServiceOperationsPortTypeSoap(WebServiceFeature... features) {
        return (ResourceImportServiceOperationsPortType)super.getPort(new QName("http://slf.com/pmapp/service/resourceimportws-ns", "ResourceImportServiceOperationsPortTypeSoap"), ResourceImportServiceOperationsPortType.class, features);
    }

}
